version: '3.9'

services:
  app:
    build:
      context: .
    volumes:
      - ./finance_yahoo_extractor_api:/app
    environment:
      - DEBUG=1
  app_migrate:
    extends:
      service: app
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput"
  app_run:
    extends:
      service: app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
